### ISSUE TITLE
只用于安卓，不用于苹果手机？

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [air-controller/air-controller-mobile#1]

**Comment by yuanhoujun** [comment]
苹果手机用iTunes 囧

**Comment by sanbeichahegongheguo** [comment]
itunes 有这个功能吗？是 iTunes store？我只搜到这个？但是在我的手机里好像用不了的感觉。

**Comment by yuanhoujun** [comment]
倒不是完全一样，但iTunes以前是官方指定的iPhone和电脑同步文件的工具，类似安卓端的手机助手。目前情况不知道是否变化。
参考地址：https://support.apple.com/zh-cn/guide/iphone/iph875319a3a/ios

**Comment by yuanhoujun** [comment]
https://support.apple.com/zh-cn/guide/mac-help/mchlde9a31f1/mac 不知道无线管理怎么用，目前手上已经没有iPhone了，不知道apple是否已经推出了无线管理iPhone的应用，但总体来说，安卓手机的一套同步方式其实不适合iPhone。

**Comment by sanbeichahegongheguo** [comment]
明白你的意思了。你这款就是专用于安卓滴，苹果的用户就用  iTunes 之类的好了。我还以为 苹果手机 也可以用这个跟 window 电脑无线连接呢。
